CREATE TABLE products
(product_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
menu_name VARCHAR(80) NOT NULL,
price FLOAT NOT NULL);

INSERT INTO products(menu_name, price) VALUES
('GOJIRA ROLL', 12.6),
('VIVA LAS VEGAS ROLL', 15.7),
('FUTOMAKI', 14.4),
('TOOTSY MAKI', 14.1),
('ZONIE ROLL', 15.5),
('NUTTY GRILLED SALAD', 10.5),
('SASHIMI SALAD', 12.0),
('SUNNY TEA', 3.75),
('COFFEE', 4.1),
('MINERAL WATER', 2.0);